# Generated by Django 3.1.1 on 2020-09-01 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=20)),
                ('lojista', models.CharField(max_length=50)),
                ('loja', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=50)),
                ('abreviatura', models.CharField(max_length=4)),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=2)),
                ('ativo', models.BooleanField(default=True)),
                ('long', models.DecimalField(decimal_places=7, max_digits=10)),
                ('lat', models.DecimalField(decimal_places=7, max_digits=10)),
            ],
        ),
    ]
