# Generated by Django 3.1.1 on 2020-09-03 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loja',
            old_name='lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='loja',
            old_name='long',
            new_name='longitude',
        ),
    ]
